/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import connection.ConnectionFactory;
import controller.ClienteController;
import controller.ProfissionalProjetoController;
import controller.ProjetoController;
import java.sql.Connection;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import model.bean.Profissional;
import model.bean.ProfissionalProjeto;
import model.bean.Projeto;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import regex.ValidaCampos;
import tablemodel.ProfissionalProjetoTableModel;
import util.StringUtil;

public class ProfissionalProjetoView extends javax.swing.JFrame {
    public Profissional profissional;
    private boolean alterar = false;
    
    ProfissionalProjetoController profissionalprojetoController;
    ClienteController clienteController;
    ProfissionalProjetoTableModel tableModelProfissionalProjeto;
    public ProfissionalProjetoView() {
        initComponents();
    }
    
    private void getListaProjetos(){
    ProjetoController projetoController = new ProjetoController();
    
    for(Projeto p : projetoController.read()){
    jComboBoxProjetos.addItem(p);
    }
    }
    
    private void getProjetosDoProfissional(){
    tableModelProfissionalProjeto = new ProfissionalProjetoTableModel(
    profissionalprojetoController.getProjetosPorProfissional(this.profissional.getIdprofissional()));
    
    jTableProfissionaisProjeto.setModel(tableModelProfissionalProjeto);
    
    jTableProfissionaisProjeto.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
    jTableProfissionaisProjeto.getColumnModel().getColumn(0).setPreferredWidth(200);
    jTableProfissionaisProjeto.getColumnModel().getColumn(1).setPreferredWidth(200);
    jTableProfissionaisProjeto.getColumnModel().getColumn(2).setPreferredWidth(200);
    jTableProfissionaisProjeto.getColumnModel().getColumn(3).setPreferredWidth(200);
    jTableProfissionaisProjeto.getColumnModel().getColumn(4).setPreferredWidth(200);
    jTableProfissionaisProjeto.getColumnModel().getColumn(5).setPreferredWidth(200); 
    limpaCampos();
    
    }
    private void limpaCampos(){
        
        jTextFieldValor.setText(StringUtil.EMPTY_FIELD);
        jTextFieldHorasTrabalhadas.setText(StringUtil.EMPTY_FIELD);
        jComboBoxProjetos.setSelectedIndex(0);
        jTextFieldValor.requestFocus();
    }
    
     private boolean validaCamposProfissionaisProjeto() {
        if(!ValidaCampos.validaValor(jTextFieldValor.getText())){
            JOptionPane.showMessageDialog(this, "Nome Inválido!");
            return false;
        }
        if(!ValidaCampos.validaHorasTrabalhadas(jTextFieldHorasTrabalhadas.getText())){
            JOptionPane.showMessageDialog(this, "Endereço Inválido!");
            return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxProjetos = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldValor = new javax.swing.JTextField();
        jTextFieldHorasTrabalhadas = new javax.swing.JTextField();
        jTextFieldProfissional = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButtonIncluir = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProfissionaisProjeto = new javax.swing.JTable();
        Imprimir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Profissional:");

        jLabel2.setText("Projeto");

        jComboBoxProjetos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        jComboBoxProjetos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProjetosActionPerformed(evt);
            }
        });

        jLabel6.setText("Valor:");

        jLabel7.setText("Horas Trabalhadas:");

        jTextFieldValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldValorKeyTyped(evt);
            }
        });

        jTextFieldHorasTrabalhadas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldHorasTrabalhadasFocusLost(evt);
            }
        });
        jTextFieldHorasTrabalhadas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldHorasTrabalhadasKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxProjetos, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldHorasTrabalhadas, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(343, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jComboBoxProjetos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jTextFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldHorasTrabalhadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(54, 92, Short.MAX_VALUE))
        );

        jTextFieldProfissional.setEditable(false);
        jTextFieldProfissional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldProfissionalActionPerformed(evt);
            }
        });

        jButtonIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/299068_add_sign_icon.png"))); // NOI18N
        jButtonIncluir.setText("Incluir");
        jButtonIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluirActionPerformed(evt);
            }
        });

        jButtonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/9027543_rotate_refresh_icon.png"))); // NOI18N
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/9004715_cross_delete_remove_cancel_icon.png"))); // NOI18N
        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jTableProfissionaisProjeto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableProfissionaisProjeto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProfissionaisProjetoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableProfissionaisProjeto);

        Imprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/print.png"))); // NOI18N
        Imprimir.setText("Imprimir");
        Imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 741, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jButtonIncluir)
                        .addGap(52, 52, 52)
                        .addComponent(jButtonSalvar)
                        .addGap(44, 44, 44)
                        .addComponent(jButtonExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(61, 61, 61)
                        .addComponent(Imprimir)
                        .addGap(97, 97, 97)))
                .addGap(12, 12, 12))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonIncluir)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButtonExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Imprimir))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldProfissional, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldProfissional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldValorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldValorKeyTyped
      
    }//GEN-LAST:event_jTextFieldValorKeyTyped

    private void jTextFieldHorasTrabalhadasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldHorasTrabalhadasFocusLost

    }//GEN-LAST:event_jTextFieldHorasTrabalhadasFocusLost

    private void jTextFieldHorasTrabalhadasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldHorasTrabalhadasKeyTyped
     
    }//GEN-LAST:event_jTextFieldHorasTrabalhadasKeyTyped

    private void jButtonIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirActionPerformed
       Projeto projeto = (Projeto) jComboBoxProjetos.getSelectedItem();
       profissionalprojetoController.create( Double.parseDouble(jTextFieldValor.getText()), jTextFieldHorasTrabalhadas.getText(), this.profissional,(Projeto) jComboBoxProjetos.getSelectedItem());
        
        this.getProjetosDoProfissional();
    }//GEN-LAST:event_jButtonIncluirActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        if (profissionalprojetoController.update(Double.parseDouble(jTextFieldValor.getText()), jTextFieldHorasTrabalhadas.getText(), this.profissional,(Projeto) jComboBoxProjetos.getSelectedItem())){
        JOptionPane.showMessageDialog(this, "Alteraçao realizada com sucesso");
    } else{
        JOptionPane.showMessageDialog(this, "Nao foi possivel realizar a alteraçao!", "Erro", JOptionPane.ERROR_MESSAGE);
    }
    this.getProjetosDoProfissional();
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        Projeto projeto = (Projeto) jComboBoxProjetos.getSelectedItem();
     if(profissionalprojetoController.delete(this.profissional.getIdprofissional(), projeto.getIdprojeto())){
        JOptionPane.showMessageDialog(this, "Exclusao realizada com sucesso!");
    } else{
         JOptionPane.showMessageDialog(this, "Nao foi possível realizar a exclusao");
     }
        
        this.getProjetosDoProfissional(); 
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jTableProfissionaisProjetoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProfissionaisProjetoMouseClicked
        tableModelProfissionalProjeto = (ProfissionalProjetoTableModel) jTableProfissionaisProjeto.getModel();
        ProfissionalProjeto profissionalProjeto = tableModelProfissionalProjeto.getProfissionalProjeto(jTableProfissionaisProjeto.getSelectedRow());
        jTextFieldValor.setText(String.valueOf(profissionalProjeto.getValor()));
        jTextFieldHorasTrabalhadas.setText(String.valueOf(profissionalProjeto.getHorastrabalhadas()));
        
        for(int i = 0; i<jComboBoxProjetos.getItemCount(); i++){
        
        Projeto p = (Projeto) jComboBoxProjetos.getItemAt(i);
        if(p.getNome().equals(profissionalProjeto.getProjeto().getNome()))
            
            jComboBoxProjetos.setSelectedIndex(i);
    }
        
        jComboBoxProjetos.setEnabled(false);
        jButtonIncluir.setEnabled(false);
        jButtonSalvar.setEnabled(false);
        jButtonExcluir.setEnabled(true);
        
        this.alterar = true;
    }//GEN-LAST:event_jTableProfissionaisProjetoMouseClicked

    private void jTextFieldProfissionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldProfissionalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldProfissionalActionPerformed

    private void ImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImprimirActionPerformed
       
        Connection con = ConnectionFactory.getConnection();
       
       String src = "src/reports/ListagemProfissionalProjetos.jasper";
       
       JasperPrint jasperPrint = null;
       Map parameters = new HashMap();
       parameters.put("idprofissional", this.profissional.getIdprofissional());
       
       try{
           jasperPrint = JasperFillManager.fillReport(src, parameters, con);
           
       }catch(JRException ex){
           
           System.out.println("Erro ao gerar relatório de profissionais: " + ex);
       }
       
       JasperViewer view = new JasperViewer(jasperPrint, false);
       view.setVisible(true);
    }//GEN-LAST:event_ImprimirActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.getListaProjetos();
    }//GEN-LAST:event_formWindowOpened

    private void jComboBoxProjetosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProjetosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxProjetosActionPerformed
  
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProfissionalProjetoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProfissionalProjetoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProfissionalProjetoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProfissionalProjetoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProfissionalProjetoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Imprimir;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonIncluir;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox<Object> jComboBoxProjetos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProfissionaisProjeto;
    private javax.swing.JTextField jTextFieldHorasTrabalhadas;
    public javax.swing.JTextField jTextFieldProfissional;
    private javax.swing.JTextField jTextFieldValor;
    // End of variables declaration//GEN-END:variables
}
