/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import filtros.FiltroParticipacao;
import controller.ProfissionalController;
import enums.FiltroParticipacaoTipoEnum;
import javax.swing.JOptionPane;
import model.bean.Profissional;
import regex.ValidaCampos;
import tablemodel.ProfissionalProjetosTableModel;
import tablemodel.ProfissionalTableModel;
import util.StringUtil;

/**
 *
 * @author aluno
 */
public class ProfissionalView extends javax.swing.JFrame {
   
    private Profissional profissional;

    ProfissionalController profissionalController = new ProfissionalController();
    ProfissionalTableModel modeloTableProfissionais;
    ProfissionalProjetosTableModel modeloTableProfissionaisProjeto;
     
    public ProfissionalView() {
        initComponents(); 
        this.getListaProfissionais();
        
    }
public void limpaCampos(){
        jTextFieldNome.setText(StringUtil.EMPTY_FIELD);
        jFormattedTextFieldCPF.setText(StringUtil.EMPTY_FIELD);
        jFormattedTextFieldTelefone.setText(StringUtil.EMPTY_FIELD);
        jTextFieldEndereco.setText(StringUtil.EMPTY_FIELD);
        jTextFieldRegprofissional.setText(StringUtil.EMPTY_FIELD);
        jTextFieldDescricao.setText(StringUtil.EMPTY_FIELD);
        jTextFieldNome.requestFocus();
    }
public void getListaProfissionais(){
        modeloTableProfissionais = new ProfissionalTableModel(profissionalController.read());        
        modeloTableProfissionaisProjeto = new ProfissionalProjetosTableModel(profissionalController.recuperarProfissionais());
        jTableProfissionais.setModel(modeloTableProfissionaisProjeto);
    }
 private boolean validaCamposProfissionais() {
        if(!ValidaCampos.validaNome(jTextFieldNome.getText())){
            JOptionPane.showMessageDialog(this, "Nome Inválido!");
            return false;
        }
        if(!ValidaCampos.validaEndereco(jTextFieldEndereco.getText())){
            JOptionPane.showMessageDialog(this, "Endereço Inválido!");
            return false;
        }
        if(!ValidaCampos.validaFone(jFormattedTextFieldTelefone.getText())){
            JOptionPane.showMessageDialog(this, "Telefone Inválido!");
            return false;
        }
        if(!ValidaCampos.validaCpf(jFormattedTextFieldCPF.getText())){
            JOptionPane.showMessageDialog(this, "CPF Inválido!");
            return false;
        }
        return true;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jFormattedTextFieldCPF = new javax.swing.JFormattedTextField();
        jFormattedTextFieldTelefone = new javax.swing.JFormattedTextField();
        jTextFieldNome = new javax.swing.JTextField();
        jButtonAdicionar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonAtualizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProfissionais = new javax.swing.JTable();
        jTextFieldEndereco = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldRegprofissional = new javax.swing.JTextField();
        jTextFieldDescricao = new javax.swing.JTextField();
        jButtonProjetos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Profissionais");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Cadastro de Profissionais");

        jLabel2.setText("Nome:");

        jLabel3.setText("CPF:");

        jLabel4.setText("Telefone:");

        jLabel5.setText("Endereço:");

        try {
            jFormattedTextFieldCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldCPFActionPerformed(evt);
            }
        });

        try {
            jFormattedTextFieldTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jButtonAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/299068_add_sign_icon.png"))); // NOI18N
        jButtonAdicionar.setText("Adicionar");
        jButtonAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarActionPerformed(evt);
            }
        });

        jButtonExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/9004715_cross_delete_remove_cancel_icon.png"))); // NOI18N
        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/9027543_rotate_refresh_icon.png"))); // NOI18N
        jButtonAtualizar.setText("Atualizar");
        jButtonAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarActionPerformed(evt);
            }
        });

        jTableProfissionais.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableProfissionais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProfissionaisMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableProfissionais);

        jLabel6.setText("Registro Profissional:");

        jLabel7.setText("Descrição:");

        jTextFieldRegprofissional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRegprofissionalActionPerformed(evt);
            }
        });

        jTextFieldDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDescricaoActionPerformed(evt);
            }
        });

        jButtonProjetos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/8542253_project_diagram_icon.png"))); // NOI18N
        jButtonProjetos.setText("Projetos");
        jButtonProjetos.setEnabled(false);
        jButtonProjetos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProjetosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(29, 29, 29)
                                .addComponent(jFormattedTextFieldCPF))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldRegprofissional, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(32, 32, 32)
                                .addComponent(jTextFieldDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(14, 14, 14))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFormattedTextFieldTelefone))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAdicionar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonExcluir)
                        .addGap(27, 27, 27)
                        .addComponent(jButtonAtualizar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonProjetos)
                        .addGap(0, 17, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldRegprofissional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jFormattedTextFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jFormattedTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonExcluir)
                    .addComponent(jButtonAtualizar)
                    .addComponent(jButtonAdicionar)
                    .addComponent(jButtonProjetos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jFormattedTextFieldCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldCPFActionPerformed

    private void jButtonAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarActionPerformed
     
               profissionalController.create(jTextFieldNome.getText(),
               jFormattedTextFieldCPF.getText(),
               jFormattedTextFieldTelefone.getText(),
               jTextFieldEndereco.getText(),
               jTextFieldRegprofissional.getText(),
               jTextFieldDescricao.getText()
               );

                jTextFieldNome.setText(StringUtil.EMPTY_FIELD);
                jFormattedTextFieldCPF.setText(StringUtil.EMPTY_FIELD);
                jFormattedTextFieldTelefone.setText(StringUtil.EMPTY_FIELD);
                jTextFieldEndereco.setText(StringUtil.EMPTY_FIELD);
                jTextFieldRegprofissional.setText(StringUtil.EMPTY_FIELD);
                jTextFieldDescricao.setText(StringUtil.EMPTY_FIELD);
                
                 this.getListaProfissionais();
        
    }//GEN-LAST:event_jButtonAdicionarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        if(jTableProfissionais.getSelectedRow() != -1){
       profissionalController.delete((int) jTableProfissionais.getValueAt(jTableProfissionais.getSelectedRow(), 0));
       
       this.getListaProfissionais();
       
       limpaCampos();
       }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jTextFieldDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDescricaoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       // this.getListaProfissionais();
    }//GEN-LAST:event_formWindowOpened

    private void jButtonAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarActionPerformed
           if(jTableProfissionais.getSelectedRow() != -1){
            profissionalController.update((int)jTableProfissionais.getValueAt(jTableProfissionais.getSelectedRow(), 0),
                    jTextFieldNome.getText(),
                    jFormattedTextFieldCPF.getText(),
                    jFormattedTextFieldTelefone.getText(),
                    jTextFieldEndereco.getText(),
                    jTextFieldRegprofissional.getText(),
                    jTextFieldDescricao.getText());
            
            this.getListaProfissionais();
            
            limpaCampos();
        }
    }//GEN-LAST:event_jButtonAtualizarActionPerformed

    private void jTableProfissionaisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProfissionaisMouseClicked
         if(jTableProfissionais.getSelectedRow() != -1){
            jButtonProjetos.setEnabled(true);
            Profissional profissional =  modeloTableProfissionais.getProfissional(jTableProfissionais.getSelectedRow());
            this.profissional = profissional;
             
            jTextFieldNome.setText(jTableProfissionais.getValueAt(jTableProfissionais.getSelectedRow(), 1).toString());
            jFormattedTextFieldCPF.setText(jTableProfissionais.getValueAt(jTableProfissionais.getSelectedRow(), 2).toString());
            jFormattedTextFieldTelefone.setText(jTableProfissionais.getValueAt(jTableProfissionais.getSelectedRow(), 3).toString());
            jTextFieldEndereco.setText(jTableProfissionais.getValueAt(jTableProfissionais.getSelectedRow(), 4).toString());
            jTextFieldRegprofissional.setText(jTableProfissionais.getValueAt(jTableProfissionais.getSelectedRow(), 5).toString());
            jTextFieldDescricao.setText(jTableProfissionais.getValueAt(jTableProfissionais.getSelectedRow(), 6).toString());
            
            jButtonExcluir.setEnabled((int)jTableProfissionais.getValueAt(jTableProfissionais.getSelectedRow(), 7)== 0);
            jButtonProjetos.setEnabled((int)jTableProfissionais.getValueAt(jTableProfissionais.getSelectedRow(), 7)== 1);
        }
    }//GEN-LAST:event_jTableProfissionaisMouseClicked

    private void jTextFieldRegprofissionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRegprofissionalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRegprofissionalActionPerformed

    private void jButtonProjetosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProjetosActionPerformed
        ParticipacaoProjetosView frmProjeto = new ParticipacaoProjetosView();
        frmProjeto.setFiltro(new FiltroParticipacao((int)jTableProfissionais.getValueAt(jTableProfissionais.getSelectedRow(), 0), FiltroParticipacaoTipoEnum.PROFISSIONAL));
        frmProjeto.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonProjetosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProfissionalView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButtonAdicionar;
    private javax.swing.JButton jButtonAtualizar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonProjetos;
    private javax.swing.JFormattedTextField jFormattedTextFieldCPF;
    private javax.swing.JFormattedTextField jFormattedTextFieldTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProfissionais;
    private javax.swing.JTextField jTextFieldDescricao;
    private javax.swing.JTextField jTextFieldEndereco;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldRegprofissional;
    // End of variables declaration//GEN-END:variables

   
}
